//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFXPatch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFXPatch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational purposes only. No ads, no music, no bullshit..
        /// </summary>
        internal static string about_hdr_desc {
            get {
                return ResourceManager.GetString("about_hdr_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPG KeyID.
        /// </summary>
        internal static string about_lbl_gpg {
            get {
                return ResourceManager.GetString("about_lbl_gpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature Thumbprint.
        /// </summary>
        internal static string about_lbl_thumbprint {
            get {
                return ResourceManager.GetString("about_lbl_thumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Repo.
        /// </summary>
        internal static string about_lnk_github {
            get {
                return ResourceManager.GetString("about_lnk_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPB Profile.
        /// </summary>
        internal static string about_lnk_tpb {
            get {
                return ResourceManager.GetString("about_lnk_tpb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bch {
            get {
                object obj = ResourceManager.GetObject("bch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_header {
            get {
                object obj = ResourceManager.GetObject("bg_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btc {
            get {
                object obj = ResourceManager.GetObject("btc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Folder.
        /// </summary>
        internal static string btn_open_folder {
            get {
                return ResourceManager.GetString("btn_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Patch.
        /// </summary>
        internal static string btn_patch {
            get {
                return ResourceManager.GetString("btn_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string btn_template_abort {
            get {
                return ResourceManager.GetString("btn_template_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string btn_template_cancel {
            get {
                return ResourceManager.GetString("btn_template_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        internal static string btn_template_ignore {
            get {
                return ResourceManager.GetString("btn_template_ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string btn_template_no {
            get {
                return ResourceManager.GetString("btn_template_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string btn_template_ok {
            get {
                return ResourceManager.GetString("btn_template_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string btn_template_retry {
            get {
                return ResourceManager.GetString("btn_template_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string btn_template_yes {
            get {
                return ResourceManager.GetString("btn_template_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chat {
            get {
                object obj = ResourceManager.GetObject("chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Dump: Exception:
        ///
        ///{0}.
        /// </summary>
        internal static string cwrite_dmp_exception {
            get {
                return ResourceManager.GetString("cwrite_dmp_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Dump: Finished.
        /// </summary>
        internal static string cwrite_dmp_finish {
            get {
                return ResourceManager.GetString("cwrite_dmp_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled by user.
        /// </summary>
        internal static string dlg_cancelled {
            get {
                return ResourceManager.GetString("dlg_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate WindowFXConfig.exe.
        /// </summary>
        internal static string dlg_title {
            get {
                return ResourceManager.GetString("dlg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eth {
            get {
                object obj = ResourceManager.GetObject("eth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamation {
            get {
                object obj = ResourceManager.GetObject("exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCH.
        /// </summary>
        internal static string lbl_contrib_bch {
            get {
                return ResourceManager.GetString("lbl_contrib_bch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC.
        /// </summary>
        internal static string lbl_contrib_btc {
            get {
                return ResourceManager.GetString("lbl_contrib_btc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETH.
        /// </summary>
        internal static string lbl_contrib_eth {
            get {
                return ResourceManager.GetString("lbl_contrib_eth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your host file has been left untouched.
        /// </summary>
        internal static string msgbox_bhost_cancel_msg {
            get {
                return ResourceManager.GetString("msgbox_bhost_cancel_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Cancelled.
        /// </summary>
        internal static string msgbox_bhost_cancel_title {
            get {
                return ResourceManager.GetString("msgbox_bhost_cancel_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate the exact path to Stardock WindowFX. You may need to manually block Stardock WindowFX using Windows Firewall.
        ///
        ///{0}.
        /// </summary>
        internal static string msgbox_bhost_fw_badpath_msg {
            get {
                return ResourceManager.GetString("msgbox_bhost_fw_badpath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Firewall Target.
        /// </summary>
        internal static string msgbox_bhost_fw_badpath_title {
            get {
                return ResourceManager.GetString("msgbox_bhost_fw_badpath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added new Firewall rules to block the executable:
        ///
        ///{0}.
        /// </summary>
        internal static string msgbox_bhost_fw_success_msg {
            get {
                return ResourceManager.GetString("msgbox_bhost_fw_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Firewall Rules.
        /// </summary>
        internal static string msgbox_bhost_fw_success_title {
            get {
                return ResourceManager.GetString("msgbox_bhost_fw_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will block WindowFX from being able to communicate with the Stardock License Server, by adding entries to your Windows host file. 
        ///
        ///Additionally, two firewall rules will be created which blocks inbound / outbound internet communication between your machine and WindowFX only.
        ///
        ///Are you sure?.
        /// </summary>
        internal static string msgbox_bhost_msg {
            get {
                return ResourceManager.GetString("msgbox_bhost_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited your host file at {0}.
        /// </summary>
        internal static string msgbox_bhost_success_msg {
            get {
                return ResourceManager.GetString("msgbox_bhost_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stardock WindowFX Servers Successfully Blocked.
        /// </summary>
        internal static string msgbox_bhost_success_title {
            get {
                return ResourceManager.GetString("msgbox_bhost_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add WindowFX Blocks?.
        /// </summary>
        internal static string msgbox_bhost_title {
            get {
                return ResourceManager.GetString("msgbox_bhost_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string msgbox_debug_fpath_env_c1_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c1_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000C-1.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c1_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} with Windows Env Var in:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c2_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c2_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000C-2.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c2_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} In:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} with Powershell in:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_ps_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_ps_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000B-0.
        /// </summary>
        internal static string msgbox_debug_fpath_ps_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_ps_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000A-0.
        /// </summary>
        internal static string msgbox_debug_fpath_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears something went wrong adding the new firewall rules.
        ///
        ///It could be that you&apos;ve already added the rules in a prior session.
        ///
        ///You can manually block Stardock WindowFX in your WIndows Firewall..
        /// </summary>
        internal static string msgbox_debug_ps_bhost_qry_alert_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_bhost_qry_alert_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall Rule Addition Failed.
        /// </summary>
        internal static string msgbox_debug_ps_bhost_qry_alert_title {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_bhost_qry_alert_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added firewall rules to system:
        ///
        ///{0}
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_ps_bhost_qry_ok_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_bhost_qry_ok_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall Updated.
        /// </summary>
        internal static string msgbox_debug_ps_bhost_qry_ok_title {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_bhost_qry_ok_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file will be backed up:
        ///
        ///{0}
        ///{1}.
        /// </summary>
        internal static string msgbox_dev_bak_msg {
            get {
                return ResourceManager.GetString("msgbox_dev_bak_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string msgbox_extract_err_title {
            get {
                return ResourceManager.GetString("msgbox_extract_err_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fails associated to this patch have a signature, however, it is not by the developer who wrote the patch, aborting...
        ///
        ///Certificate Thumbprint:
        ///     {0}.
        /// </summary>
        internal static string msgbox_integrity_fail_msg {
            get {
                return ResourceManager.GetString("msgbox_integrity_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files for this activator are not signed and may be fake from another source. Files from this activator&apos;s developer will ALWAYS be signed.
        ///
        ///Ensure you downloaded this patch from the developer.
        ///
        ///Failed File(s):
        ///     {0}.
        /// </summary>
        internal static string msgbox_integrity_fail_nosign_msg {
            get {
                return ResourceManager.GetString("msgbox_integrity_fail_nosign_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity Check Failed.
        /// </summary>
        internal static string msgbox_integrity_fail_nosign_title {
            get {
                return ResourceManager.GetString("msgbox_integrity_fail_nosign_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity Check Failed.
        /// </summary>
        internal static string msgbox_integrity_fail_title {
            get {
                return ResourceManager.GetString("msgbox_integrity_fail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find WindowFX. It must be installed first before you can run the patcher..
        /// </summary>
        internal static string msgbox_nolocopen_msg {
            get {
                return ResourceManager.GetString("msgbox_nolocopen_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowFX Not Found.
        /// </summary>
        internal static string msgbox_nolocopen_title {
            get {
                return ResourceManager.GetString("msgbox_nolocopen_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patcher cannot determine where WindowFX is installed
        ///Tried looking in {0}
        ///
        ///You will be prompted to manually locate WindowFXConfig.exe. Ensure that WindowFX is installed on your system..
        /// </summary>
        internal static string msgbox_nolocpath_msg {
            get {
                return ResourceManager.GetString("msgbox_nolocpath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Locate WindowFX.
        /// </summary>
        internal static string msgbox_nolocpath_title {
            get {
                return ResourceManager.GetString("msgbox_nolocpath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowFX has been successfully patched..
        /// </summary>
        internal static string msgbox_patch_compl_msg {
            get {
                return ResourceManager.GetString("msgbox_patch_compl_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Complete.
        /// </summary>
        internal static string msgbox_patch_compl_title {
            get {
                return ResourceManager.GetString("msgbox_patch_compl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update v{0} is available.
        ///
        ///Updates ensure this patch works with the latest version {1}. If you have issues using this tool, download the latest version in the top menu: Help ► Updates
        ///
        ///Would you like to view the update? If not, program will start as normal..
        /// </summary>
        internal static string msgbox_update_msg {
            get {
                return ResourceManager.GetString("msgbox_update_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available: {0} ► {1}.
        /// </summary>
        internal static string msgbox_update_title {
            get {
                return ResourceManager.GetString("msgbox_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating backup {0} ....
        /// </summary>
        internal static string status_bak_create {
            get {
                return ResourceManager.GetString("status_bak_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying patch {0}% ....
        /// </summary>
        internal static string status_byte_modify {
            get {
                return ResourceManager.GetString("status_byte_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0}.
        /// </summary>
        internal static string status_dlg_loaded {
            get {
                return ResourceManager.GetString("status_dlg_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Patch to begin ....
        /// </summary>
        internal static string status_generate {
            get {
                return ResourceManager.GetString("status_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity check failed.
        /// </summary>
        internal static string status_integrity_fail {
            get {
                return ResourceManager.GetString("status_integrity_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity check success.
        /// </summary>
        internal static string status_integrity_success {
            get {
                return ResourceManager.GetString("status_integrity_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching {0} ....
        /// </summary>
        internal static string status_launch_app {
            get {
                return ResourceManager.GetString("status_launch_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowFX not found, loading manual dialog ....
        /// </summary>
        internal static string status_manual_locate {
            get {
                return ResourceManager.GetString("status_manual_locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully patched WindowFX.
        /// </summary>
        internal static string status_patch_complete {
            get {
                return ResourceManager.GetString("status_patch_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating {0} ....
        /// </summary>
        internal static string status_patch_locating {
            get {
                return ResourceManager.GetString("status_patch_locating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, applying patch ....
        /// </summary>
        internal static string status_patch_start {
            get {
                return ResourceManager.GetString("status_patch_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping {0} services ....
        /// </summary>
        internal static string status_services_stopping {
            get {
                return ResourceManager.GetString("status_services_stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not kill {0}.
        /// </summary>
        internal static string status_taskkill_fail {
            get {
                return ResourceManager.GetString("status_taskkill_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restart task {0}.
        /// </summary>
        internal static string status_taskkill_fail_cmd {
            get {
                return ResourceManager.GetString("status_taskkill_fail_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not kill task {0}.
        /// </summary>
        internal static string status_taskkill_fail_proc {
            get {
                return ResourceManager.GetString("status_taskkill_fail_proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped service {0} ....
        /// </summary>
        internal static string status_taskkill_succ {
            get {
                return ResourceManager.GetString("status_taskkill_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowFX not found.
        /// </summary>
        internal static string status_wfx_not_found {
            get {
                return ResourceManager.GetString("status_wfx_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do this because I enjoy giving back, and I&apos;m not looking to make a profit off my work. However, donations would help immensely for one purpose -- purchasing libraries and other commercial products which have insane licensing systems. These types of products would make life much easier and get releases pumped out on a more regular basis. Don&apos;t feel obligated, this is just &quot;if you can&quot;. My main goal is better tools..
        /// </summary>
        internal static string txt_contrib_intro {
            get {
                return ResourceManager.GetString("txt_contrib_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program will patch and activate WindowFX. Ensure that you install Stardock WindowFX before running this patch..
        /// </summary>
        internal static string txt_intro_1 {
            get {
                return ResourceManager.GetString("txt_intro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press PATCH to begin.
        /// </summary>
        internal static string txt_intro_2 {
            get {
                return ResourceManager.GetString("txt_intro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon wfx_128 {
            get {
                object obj = ResourceManager.GetObject("wfx_128", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
