//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFXPatch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aetherinox")]
        public string app_dev_name {
            get {
                return ((string)(this["app_dev_name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58a1539d6988d76f44bae27c27ed5645d3b1222a")]
        public string app_dev_piv_thumbprint {
            get {
                return ((string)(this["app_dev_piv_thumbprint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CB5C4C30CD0D4028")]
        public string app_dev_gpg_keyid {
            get {
                return ((string)(this["app_dev_gpg_keyid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Aetherinox/windowfx-patcher")]
        public string app_url_github {
            get {
                return ((string)(this["app_url_github"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://thepiratebay.org/user/Aetherinox")]
        public string app_url_tpb {
            get {
                return ((string)(this["app_url_tpb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WindowFXConfig.exe")]
        public string app_target_exe {
            get {
                return ((string)(this["app_target_exe"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bShowedUpdates {
            get {
                return ((bool)(this["bShowedUpdates"]));
            }
            set {
                this["bShowedUpdates"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/Aetherinox/windowfx-patcher/master/Manifest/man" +
            "ifest.json")]
        public string app_url_manifest {
            get {
                return ((string)(this["app_url_manifest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WindowFX")]
        public string app_name {
            get {
                return ((string)(this["app_name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wfx4.dll")]
        public string app_res_file_1 {
            get {
                return ((string)(this["app_res_file_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wfx4_64.dll")]
        public string app_res_file_2 {
            get {
                return ((string)(this["app_res_file_2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wfx32.exe")]
        public string app_res_file_3 {
            get {
                return ((string)(this["app_res_file_3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wfx64.exe")]
        public string app_res_file_4 {
            get {
                return ((string)(this["app_res_file_4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("947c06abf78cd9d8090f7c22811e3ae27ed1a064c52aaba9baf19b848efecbb6")]
        public string app_res_hash_1 {
            get {
                return ((string)(this["app_res_hash_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84002da39b52671b5092b24da5f0ea878287c9533dc7e53abcb758e0b72793fa")]
        public string app_res_hash_2 {
            get {
                return ((string)(this["app_res_hash_2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1647a0ebbe13ecb56c3320878e0e2d44b2554dde2a0a89f1ec26729d6c072c6a")]
        public string app_res_hash_3 {
            get {
                return ((string)(this["app_res_hash_3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7098244dc62c38d726e4070c1594d4f3f830f65556469e45c5c8b1385a3e8ff0")]
        public string app_res_hash_4 {
            get {
                return ((string)(this["app_res_hash_4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("womtrust.dll")]
        public string app_res_file_womdll {
            get {
                return ((string)(this["app_res_file_womdll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wontrust.dll")]
        public string app_res_file_wondll {
            get {
                return ((string)(this["app_res_file_wondll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hex_original.dmp")]
        public string app_res_file_dmp_original {
            get {
                return ((string)(this["app_res_file_dmp_original"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hex_patched.dmp")]
        public string app_res_file_dmp_patched {
            get {
                return ((string)(this["app_res_file_dmp_patched"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool app_bDevmode {
            get {
                return ((bool)(this["app_bDevmode"]));
            }
            set {
                this["app_bDevmode"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--debug")]
        public string app_argid_debug {
            get {
                return ((string)(this["app_argid_debug"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NeedsUpgrade {
            get {
                return ((bool)(this["NeedsUpgrade"]));
            }
            set {
                this["NeedsUpgrade"] = value;
            }
        }
    }
}
